### ISSUE TITLE
Implement Login Form

### ISSUE THREAD

**Issue by thomas-clifford** [NicolasCapparelli/senior-project#5]
After clicking the "login" button on the home screen, a form should pop up, allowing the user to enter their credentials. If they enter the information of an existing user in the database, they should be navigated to either the doctor dashboard or the client dashboard depending on their assignment (client or doctor).

The login page should allow the user to enter the following:
- Email
- Password

**Comment by thompsond** [comment]
The login form exists, but it is not currently connected to the database.
